const users = [
  {
    id: "64b1f1a3e1d88e001f9d8b1a",
    email: "john.doe@example.com",
    username: "johndoe",
    password: "password123",
    room: 1101,
    name: "John Doe",
    instituteId: "12345",
    hobbies: "Reading, Music",
    avatar: "/images/johndoe.jpg",
    whatsapp: "https://wa.me/123456789",
    instagram: "https://instagram.com/johndoe",
    linkedin: "https://linkedin.com/in/johndoe",
    createdAt: new Date(),
  },
  {
    id: "64b1f1a3e1d88e001f9d8b1b",
    email: "jane.smith@example.com",
    username: "janesmith",
    password: "password456",
    room: 2102,
    name: "Jane Smith",
    instituteId: "54321",
    hobbies: "Sports, Coding",
    avatar: "/images/janesmith.jpg",
    whatsapp: "https://wa.me/987654321",
    instagram: "https://instagram.com/janesmith",
    linkedin: "https://linkedin.com/in/janesmith",
    createdAt: new Date(),
  },
  {
    id: "64b1f1a3e1d88e001f9d8b1c",
    email: "alice.johnson@example.com",
    username: "alicejohnson",
    password: "password789",
    room: 2103,
    name: "Alice Johnson",
    instituteId: "23456",
    hobbies: "Photography, Traveling",
    avatar: "/images/alicejohnson.jpg",
    whatsapp: "https://wa.me/123456780",
    instagram: "https://instagram.com/alicejohnson",
    linkedin: "https://linkedin.com/in/alicejohnson",
    createdAt: new Date(),
  },
  {
    id: "64b1f1a3e1d88e001f9d8b1d",
    email: "bob.brown@example.com",
    username: "bobbrown",
    password: "password101",
    room: 2104,
    name: "Bob Brown",
    instituteId: "65432",
    hobbies: "Gaming, Music",
    avatar: "/images/bobbrown.jpg",
    whatsapp: "https://wa.me/987654320",
    instagram: "https://instagram.com/bobbrown",
    linkedin: "https://linkedin.com/in/bobbrown",
    createdAt: new Date(),
  },
  {
    id: "64b1f1a3e1d88e001f9d8b1e",
    email: "charlie.davis@example.com",
    username: "charliedavis",
    password: "password202",
    room: 2105,
    name: "Charlie Davis",
    instituteId: "34567",
    hobbies: "Cooking, Hiking",
    avatar: "/images/charliedavis.jpg",
    whatsapp: "https://wa.me/123456781",
    instagram: "https://instagram.com/charliedavis",
    linkedin: "https://linkedin.com/in/charliedavis",
    createdAt: new Date(),
  },
  {
    id: "64b1f1a3e1d88e001f9d8b1f",
    email: "diana.green@example.com",
    username: "dianagreen",
    password: "password303",
    room: 2106,
    name: "Diana Green",
    instituteId: "76543",
    hobbies: "Reading, Yoga",
    avatar: "/images/dianagreen.jpg",
    whatsapp: "https://wa.me/987654322",
    instagram: "https://instagram.com/dianagreen",
    linkedin: "https://linkedin.com/in/dianagreen",
    createdAt: new Date(),
  },
  {
    id: "64b1f1a3e1d88e001f9d8b20",
    email: "ethan.white@example.com",
    username: "ethanwhite",
    password: "password404",
    room: 2107,
    name: "Ethan White",
    instituteId: "45678",
    hobbies: "Fitness, Traveling",
    avatar: "/images/ethanwhite.jpg",
    whatsapp: "https://wa.me/123456782",
    instagram: "https://instagram.com/ethanwhite",
    linkedin: "https://linkedin.com/in/ethanwhite",
    createdAt: new Date(),
  },
  {
    id: "64b1f1a3e1d88e001f9d8b21",
    email: "fiona.black@example.com",
    username: "fionablack",
    password: "password505",
    room: 2108,
    name: "Fiona Black",
    instituteId: "87654",
    hobbies: "Gardening, Painting",
    avatar: "/images/fionablack.jpg",
    whatsapp: "https://wa.me/987654323",
    instagram: "https://instagram.com/fionablack",
    linkedin: "https://linkedin.com/in/fionablack",
    createdAt: new Date(),
  },
  {
    id: "64b1f1a3e1d88e001f9d8b22",
    email: "george.hill@example.com",
    username: "georgehill",
    password: "password606",
    room: 2109,
    name: "George Hill",
    instituteId: "56789",
    hobbies: "Coding, Reading",
    avatar: "/images/georgehill.jpg",
    whatsapp: "https://wa.me/123456783",
    instagram: "https://instagram.com/georgehill",
    linkedin: "https://linkedin.com/in/georgehill",
    createdAt: new Date(),
  },
  {
    id: "64b1f1a3e1d88e001f9d8b23",
    email: "hannah.adams@example.com",
    username: "hannahadams",
    password: "password707",
    room: 2110,
    name: "Hannah Adams",
    instituteId: "98765",
    hobbies: "Traveling, Drawing",
    avatar: "/images/hannahadams.jpg",
    whatsapp: "https://wa.me/987654324",
    instagram: "https://instagram.com/hannahadams",
    linkedin: "https://linkedin.com/in/hannahadams",
    createdAt: new Date(),
  },
];
